### ISSUE TITLE
Possible Dependencies

### ISSUE THREAD

**Issue by LE0616** [benetech/Imageshare-Extensions#1]
While it took more time to set up, the following dependencies resulted in very clear debugging and a kind of simplified CSS inline:
  "devDependencies": {
    "autoprefixer": "^10.1.0",
    "parcel": "^2.0.0-nightly.486",
    "postcss-import": "^14.0.0"
  },
  "dependencies": {
    "crx-hotreload": "^1.0.6",
    "tailwindcss": "^2.0.2"
  }
 
Links for more information: 
- autoprefixer: https://autoprefixer.github.io/
- parcel (bundler): https://parceljs.org/
- postcss-import: https://www.npmjs.com/package/postcss-import
- crx-hotreload (watcher): https://github.com/xpl/crx-hotreload
- tailwindcss: https://tailwindcss.com/

While the debugging process was a joy, so yay on the watcher and bundler, I'm really not sure how I feel about putting CSS inline. Part of me very much prefers having things separated into their own files, however for the small amount of HTML we'll be needing I can see the appeal. What are your thoughts? Do you have tools that you've liked better?

**Comment by sinabahram** [comment]
Awesome stuff! I'll defer to @jkva  about specific libraries and code hygiene as we tend to agree on such things, but I'll offer the following advice/guidance as meta-rules. Please push back on any of them so we all land on what we feel is comfortable/best practice.

* Code should be separated out as much as possible, but not to the point of making it harder to find something than to code something.
* Production output should be minified, optimized, etc. as tightly and efficiently as possible (good tools exist to do this for us of course).
* Staging/testing output should be super easy to read. Don't optimize a thing so we can always converse about exact markup as you wrote it (or close enough, anyways). Note, technically this means I'm asking for us to do dev/staging/production because in staging, the output should be identical to production, but also we can just go dev to production on this project unless if @jkva  objects.
* Whatever we use must ensure that we have complete and absolute control over every single aspect of markup for accessibility reasons.
* RE updates, let's make sure that we get automatic updates for all dot releases, but not for major versions. Node packages update every second of every day, so we don't want to miss a security or other update. I say this because your version strings seem hard coded, but i could be reading it incorrectly, and they are already coded as I've described. If so, apologies.

That's what I got for now. I welcome any thoughts.

**Comment by LE0616** [comment]
Noted and no pushback needed. Just one question RE updates:

- In my above package.json dependencies, they are coded as ^10.1.0. Am I understanding correctly that this means that npm can update to patch and minor releases: 10.1.1, 10.2.0, and so on, but not for major version changes that break compatibility, which means, in this example, 11.0 and higher? That's your preference for update rules right?  It's the ^ that creates that distinction?

**Comment by LE0616** [comment]
With the above dependencies assumed, for now, the file layout might look something like this:

> Imageshare-search
&emsp;     > src
&emsp;&emsp;          - background.js
&emsp;&emsp;          - main.html
&emsp;&emsp;          - main.js
&emsp;&emsp;          - options.html
&emsp;&emsp;          - options.js
&emsp;&emsp;          - manifest.json
&emsp;&emsp;          - style.css
&emsp;     > dist (local only)
&emsp;     > node_modules (ignored)
&emsp;     > .parcel-cache (local only, I think)
&emsp;     - package-lock.json
&emsp;     - package.json
&emsp;     - postcss.config.css
&emsp;     - tailwind.config.css

**Comment by sinabahram** [comment]
Yes, and this source on [semver syntax](https://semver.npmjs.com/) seems to confirm that understanding.

**Comment by jkva** [comment]
Any particular reason for using tailwind? In my experience it's barely a step away from inline css, we lose the cascade and forego semantic classes. Is there an expectation of CSS complexity cases where tooling like tailwind helps out?

Other than that, thumbs-up on all the above.

**Comment by LE0616** [comment]
No, that was the one I wasn't so keen on myself. I'm game to drop it.

**Comment by jkva** [comment]
Closing as covered by development into build targets.
