### ISSUE TITLE
Icon missing when pinned to the toolbar

### ISSUE THREAD

**Issue by clapierre** [benetech/Imageshare-Extensions#29]
Chrome: Canary mv3 (Mac)

When I pinned the Imageshare plugin to the toolbar space was made for the Icon but its blank as shown in this screenshot.

![Screenshot of chrome browser toolbar: showing no Imageshare Icon, instead an empty space present.](https://user-images.githubusercontent.com/7736749/115595934-62b3be00-a28c-11eb-9a1f-a903c34158d1.png)

However when I click on that blank space to the left of the normal puzzle piece icon representing plugins the Imageshare dropdown appears and the Imageshare Icon is vaguely shown in a very light gray color as shown in this screenshot.

![Screenshot of chrome browser toolbar: once empty space is selected the imageshare icon is vaguely present light gray on white and reveals the Standard and Advance Search options.](https://user-images.githubusercontent.com/7736749/115595954-68a99f00-a28c-11eb-8a33-0ee644799f51.png)

**Comment by clapierre** [comment]
Furthermore, in Firefox the Icon is white as well and very difficult to see on the toolbar.

![screenshot of Firefox's toolbar with the barely seen Imageshare logo one needs to click on to bring up the search options.](https://user-images.githubusercontent.com/7736749/115766836-4764b380-a35d-11eb-96e8-d2ae0782e637.png)

**Comment by LE0616** [comment]
The color requirements for icons vary from context to context as well as browser to browser but this is something that will be resolved with build targets.  I've created white or inverted versions of all the icons so both white and black versions are ready to go. The build targets will tell the program which icon to pull when. 

@jkva Is there a way to say "if dark mode" and switch colors then as well or is that something the browser usually handles? I ask because on my computer which is in dark mode it's the black versions of the icons that are hard to see.

**Comment by sinabahram** [comment]
https://css-tricks.com/dark-modes-with-css/
